import os

GOOGLE_CLIENT_ID = os.getenv('GOOGLE_CLIENT_ID')
GOOGLE_CLIENT_SECRET = os.getenv('GOOGLE_CLIENT_SECRET')

ACTIONSTEP_CLIENT_SECRET = '9B22LHAAWHS0RKS385INK0TNZHZNGWJOSEF7OQKKQPCB2NOYIZYNA'
ACTIONSTEP_CLIENT_ID = 'G5HOL0EQST6DJDYJOSEFXGEAV7236ZNM5TUHFECV3O64PDG5PYM8EH3Q5W'
